# Generated by Django 4.0.1 on 2022-02-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0002_user_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
